#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Feb 12 16:26:57 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class VerImagenYTexto(wx.ScrolledWindow):
    '''
    classdocs
    '''
    
    def __init__(self, *args, **kwds):
        '''
        Constructor
        '''
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self.sBImagen = wx.StaticBitmap(self, -1)
        self.tCtrlInfoTweet = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_AUTO_URL)
        self.__set_properties()
        self.__do_layout()
        
    def __set_properties(self):
        self.tCtrlInfoTweet.SetMinSize((600, 100))
        #self.sBImagen.SetMinSize((600, 500))
        
        
    def __do_layout(self):
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.sBImagen, 0, 0, 0)
        sizer_2.Add(self.tCtrlInfoTweet, 0, 0, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
    
    #def anyadirURL(self, url):
    #    self.tCUrl.SetValue(url)
    
    def anyadirTexto(self, texto):
        self.tCtrlInfoTweet.SetValue(texto)
    
    def anyadirImagen(self, rutaImagen):
        #Ajustar la imagen a un tamaño antes de mostrarla por pantalla (no guardarla 
        #con este nuevo tamaño). ¡Cuidado con la relación ancho*alto!
        imagen = wx.Image(rutaImagen,wx.BITMAP_TYPE_ANY)
        #1º fijo un alto (280px).
        nuevoAlto = 300
        #2º Extraer ancho y alto.
        viejoAncho, viejoAlto = imagen.GetSize()
        #3º Por regla de tres calculamos el ancho: nuevoAncho=(nuevoAlto*viejoAncho)/viejoAlto.
        nuevoAncho=(nuevoAlto*viejoAncho)/viejoAlto
        #4º Reduzco imagen al nuevo tamaño (sin guardarla).
        imagen.Rescale(nuevoAncho,nuevoAlto,quality=wx.IMAGE_QUALITY_HIGH)
        #5º Muestro imagen reducida por pantalla.
        self.sBImagen.SetBitmap(bitmap=imagen.ConvertToBitmap())
        
    

# end of class VerImagenYTexto


#class MyApp(wx.App):
#    def OnInit(self):
#        wx.InitAllImageHandlers()
#        vIYT = VerImagenYTexto(None, -1, "")
#        self.SetTopWindow(vIYT)
#        vIYT.Show()
#        return 1

# end of class MyApp

#if __name__ == "__main__":
#    app = MyApp(0)
#    app.MainLoop()
