#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Feb  9 22:46:33 2011

import os
import wx
import modelos

# begin wxGlade: extracode
# end wxGlade



class SubirImagenATwitpic(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SubirImagenATwitpic.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.tcRutaImagen = wx.TextCtrl(self, -1, "", style=wx.TE_READONLY)
        self.btRutaImagen = wx.Button(self, -1, "Examinar...")
        self.tcTexto = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_MULTILINE|wx.TE_AUTO_URL)
        self.btCancelar = wx.Button(self, -1, "Cancelar")
        self.btAceptar = wx.Button(self, -1, "Aceptar")

        self.__set_properties()
        self.__do_layout()
        
        self.btAceptar.Bind(wx.EVT_BUTTON, self.subirATwitpic)
        self.btRutaImagen.Bind(wx.EVT_BUTTON, self.examinarImagen)
        self.btCancelar.Bind(wx.EVT_BUTTON, self.salir)
        # end wxGlade
    
    def salir(self, evento=None):
        self.Destroy()
    
    def examinarImagen(self, evento=None):
        dialogoCargar=wx.FileDialog(self, "Elige una imagen", "", "", "*.*", wx.FD_OPEN)
        dialogoCargar.SetDirectory(os.path.realpath(""))
        i=dialogoCargar.ShowModal()
        if i== wx.ID_OK:
            rutaFichOrigen=dialogoCargar.GetPath()
            self.tcRutaImagen.Clear()
            self.tcRutaImagen.AppendText(rutaFichOrigen)
    
    def subirATwitpic(self, evento=None):
        if (self.tcRutaImagen.GetValue()!="") and (self.tcTexto.GetValue()!=""):
            co = modelos.Comunes()
            co.enviarImagenATimeline(self.tcRutaImagen.GetValue(), self.tcTexto.GetValue())
            self.salir()
    
    def __set_properties(self):
        # begin wxGlade: SubirImagenATwitpic.__set_properties
        self.SetTitle("Subir imagen a Twitpic")
        self.tcRutaImagen.SetMinSize((332, 27))
        self.tcTexto.SetMinSize((418, 182))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SubirImagenATwitpic.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_2.Add(self.tcRutaImagen, 0, 0, 0)
        grid_sizer_2.Add(self.btRutaImagen, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.tcTexto, 0, 0, 0)
        grid_sizer_3.Add(self.btCancelar, 0, 0, 0)
        grid_sizer_3.Add((248, 27), 0, 0, 0)
        grid_sizer_3.Add(self.btAceptar, 0, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class SubirImagenATwitpic
